### ISSUE TITLE
Use modern.dev

### ISSUE THREAD

**Issue by linonetwo** [ahanniga/tiddlywiki-context-menu-plugin#3]
https://github.com/tiddly-gittly/Modern.TiddlyDev

Do you need a PR?

Also I'd like to add some features to this, are you there to accept PRs? Or may I just fork this to https://github.com/tiddly-gittly and publish my releases?

**Comment by linonetwo** [comment]
I just want to dev using ts

**Comment by ahanniga** [comment]
Hi, it's probably best simply to fork the code and produce a typescript version?

**Comment by linonetwo** [comment]
Oh, I haven't see this. Since you are still updating it, I don't want to split the community by forking it.
