### ISSUE TITLE
New Here with multi word title

### ISSUE THREAD

**Issue by s5rockhoppers** [ahanniga/tiddlywiki-context-menu-plugin#4]
If you try and use the 'New Here' option on a tiddler that has a multi-word title it will create a tag for each word in the title. 

I fixed this by adding [[ around the `targ` variable, but I'm sure there is a more proper way to do it.

```
case "tm-new-here":
    targ = "[[" + targ + "]]";
    this.dispatchEvent({ type: "tm-new-tiddler", paramObject: {tags: targ}});
break;
```

**Comment by ahanniga** [comment]
Well spotted! Will take a look.
