### ISSUE TITLE
Icons no longer displayed since 5.3.0

### ISSUE THREAD

**Issue by superuser-does** [ahanniga/tiddlywiki-context-menu-plugin#5]
Hello, I am a new user of the plugin and I have confirmed this issue on a blank TiddlyWiki where the context menu fails to show icons.
![Tiddlywiki shows parameters](https://github.com/ahanniga/tiddlywiki-context-menu-plugin/assets/32982579/464d99ba-3908-4d41-b43e-6117edfeeea7)

Looking at the documentation for the latest breaking version, the changelog for 5.3.0 suggests a cause:
> [Core Icons](https://tiddlywiki.com/#Core%20Icons) to allow the size to be controlled with a parameter
> ⚠️ This change can cause problems with non-standard usage of the core icons where the text is directly rendered instead of being transcluded

I would be grateful if you would consider an update to match the approach in the latest version.

**Comment by ahanniga** [comment]
Back on Tiddlywiki again, apologies for the late response. Fixed in 0.9.0.
